### ISSUE TITLE
Peruse does not close properly

### ISSUE THREAD

**Issue by Folaht** [joshuef/peruse#100]
OS: Arch Linux

Process:

Close the Peruse window by last tab close or window close.

Expectation:

The window closes and the process ends.

Result:

The window closes, but `ps -ef | grep peruse` shows that the process is still running.

**Comment by b-zee** [comment]
I also have this problem in Windows 10.

Consequently, when launching the browser again (after the above issue; so with the Peruse process still running but the GUI closed) the GUI won't re-open. I assume @Folatt also had this problem causing him to look whether something was wrong with the process.

**Comment by hunterlester** [comment]
Migrated issue to https://github.com/maidsafe/safe_browser/issues/313

**Comment by S-Coyle** [comment]
@Folatt a courtesy message to advise that this issue is now fixed in today's Peruse 0.7.0 release over on the MaidSafe GitHub - https://github.com/maidsafe/safe_browser/releases/tag/peruse-browser-0.7.0
