### ISSUE TITLE
Peruse Dev --preload does not work on Linux

### ISSUE THREAD

**Issue by happybeing** [joshuef/peruse#101]
Trying this with Peruse Dev 0.6 I can't get `--preload` working on Ubuntu 18.

Following the instructions here: https://github.com/joshuef/peruse#debugging I've tried a few ways to start Peruse Dev, including this for example:

```
NODE_ENV=dev ~/bin/pbdev --mock --preload
```

Note that the above does give me a mock network, but no preloaded account. I did create one with username and credentials `mocksafenetworkdeveloper` which shows that the account was not preloaded. To confirm the args are being picked up I was able to access the live network with:
```
NODE_ENV=dev ~/bin/pbdev --live
```

**Comment by hunterlester** [comment]
Migrating to: https://github.com/maidsafe/safe_browser/issues/314
