### ISSUE TITLE
Some sites fail with segmentation fault

### ISSUE THREAD

**Issue by JPL1** [joshuef/peruse#15]
see e.g. safe://safe-blues.jpl (browser crashes straight away), safe://optomoon.draw (browser crashes after 9s)

**Comment by joshuef** [comment]
I'd wager this is to do with partial content headers, as it's with mp3 and video that it's failing. 

I'll take a deeper dive shortly and investigate as/when i'm on the streaming implementation. 

In the meantime, if you're able to garner any useful logs, please post them.

Thanks @JPL1!

**Comment by JPL1** [comment]
No problem. Please see attached logfiles for safe-blues.jpl and optomoon.draw crashes plus screenshot of Windows console.
[authenticator-optomoon-draw.log](https://github.com/joshuef/peruse/files/1576805/authenticator-optomoon-draw.log)
[authenticator-safe-blues-jpl.log](https://github.com/joshuef/peruse/files/1576806/authenticator-safe-blues-jpl.log)
![cmd-optomoon-draw](https://user-images.githubusercontent.com/12783198/34225182-62c6e988-e5bd-11e7-9d4e-0a2601e4caff.png)
![cmd-safe-blues jpl](https://user-images.githubusercontent.com/12783198/34225184-62e4c624-e5bd-11e7-8c04-6d3c82eb7064.png)
[Peruse_Browser.Maidsafe_Ltd-optomoon-draw.log](https://github.com/joshuef/peruse/files/1576807/Peruse_Browser.Maidsafe_Ltd-optomoon-draw.log)
[Peruse_Browser.Maidsafe_Ltd-safe-blues-jpl.log](https://github.com/joshuef/peruse/files/1576808/Peruse_Browser.Maidsafe_Ltd-safe-blues-jpl.log)

**Comment by joshuef** [comment]
No longer an issue on master.
