### ISSUE TITLE
peruse 0.3.4 segmentation fault

### ISSUE THREAD

**Issue by grynca** [joshuef/peruse#29]
hello,
i tried peruse-v0.3.4-linux-x64.zip binary.
After authenticating and going to:
safe://jamz.audity
browser crashes with Segmentation fault.
Reproduction:
The page opens another tab in my other browser (Chrome) - which i have open on other monitor.
When i close it and focus again Peruse (click anywhere into its window) it crashes.

**Comment by joshuef** [comment]
Sorry for slow response here, I'd totally missed this.

So: It's opening another tab as you're attempting to open youtube links which are disabled (insecure) in Peruse. So it hands this off to the system.

Using latest Peruse (0.4.1) I'm not able to repro the segfault. Please let me know if you're still experiencing this in the latest peruse browser.

**Comment by joshuef** [comment]
Closing as cannot repro
