### ISSUE TITLE
navigating by manually typing new url

### ISSUE THREAD

**Issue by lobogang** [joshuef/peruse#8]
current
---
- [x] typing url then `enter` doesnt work
- [ ] no `go` icon in url bar

wanted
---
both of these should be implemented

**Comment by joshuef** [comment]
Half of this was sorted by some commits I'd forgotten to push :|

**Comment by joshuef** [comment]
>  no go icon in url bar

What's this mean, @lobogang ?

**Comment by lobogang** [comment]
It means a button analog for pressing enter after typing a URL.

**Comment by joshuef** [comment]
dont think this is needed, closing.
