### ISSUE TITLE
Continual relaunching of new tabs when going to invite server

### ISSUE THREAD

**Issue by nadiaburborough** [joshuef/peruse#90]
When creating an account for mock via the authenticator, click **Create Account**, then **Claim an invitation token**. A new tab opens in Peruse which then invokes a new tab to the invite server in the web browser I already had open (Chrome). It then continued to open more and more new tabs in Chrome until I killed Peruse. It should have only opened one and stopped there.

I'm on OSX

**Comment by joshuef** [comment]
This should be fixed.
